stages:
- build
- test

ubuntu-windows-cross-compile:
  stage: build
  tags:
  - docker
  - linux
  - my_runner
  image: ubuntu:18.04
  script:
  - apt-get update -y
  - apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget curl bsdmainutils automake mingw-w64 -y
  - update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
  - update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
  - HOST=x86_64-w64-mingw32 ./zcutil/build.sh -j$(nproc)
  artifacts:
    paths:
#    - ./src/zcashd.exe
#    - ./src/zcash-cli.exe
#    - ./src/zcash-gtest.exe
#    - ./src/zcash-tx.exe
    - ./src/test/test_bitcoin.exe

windows-DoS_banning:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --log_sink=stdout
    --report_level=detailed
    --report_format=XML
    --report_sink=DoS_banning_report.xml
    --run_test=DoS_tests/DoS_banning
  allow_failure: true
  artifacts:
    paths:
    - ./DoS_banning_report.xml
    reports:
      junit:
      - ./DoS_banning_report.xml

.windows-DoS_banscore:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=DoS_banscore_report.xml
    --run_test=DoS_tests/DoS_banscore
  allow_failure: true
  artifacts:
    paths:
    - ./DoS_banscore_report.xml
    reports:
      junit:
      - ./DoS_banscore_report.xml

.windows-DoS_bantime:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=DoS_bantime_report.xml
    --run_test=DoS_tests/DoS_bantime
  allow_failure: true
  artifacts:
    paths:
    - ./DoS_bantime_report.xml
    reports:
      junit:
      - ./DoS_bantime_report.xml

.windows-netbase_networks:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=netbase_networks_report.xml
    --run_test=netbase_tests/netbase_networks
  allow_failure: true
  artifacts:
    paths:
    - ./netbase_networks_report.xml
    reports:
      junit:
      - ./netbase_networks_report.xml

.windows-netbase_properties:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=netbase_properties_report.xml
    --run_test=netbase_tests/netbase_properties
  allow_failure: true
  artifacts:
    paths:
    - ./netbase_properties_report.xml
    reports:
      junit:
      - ./netbase_properties_report.xml

.windows-netbase_lookupnumeric:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=netbase_lookupnumeric_report.xml
    --run_test=netbase_tests/netbase_lookupnumeric
  allow_failure: true
  artifacts:
    paths:
    - ./netbase_lookupnumeric_report.xml
    reports:
      junit:
      - ./netbase_lookupnumeric_report.xml

.windows-onioncat_test:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=onioncat_test_report.xml
    --run_test=netbase_tests/onioncat_test
  allow_failure: true
  artifacts:
    paths:
    - ./onioncat_test_report.xml
    reports:
      junit:
      - ./onioncat_test_report.xml

.windows-subnet_test:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=subnet_test_report.xml
    --run_test=netbase_tests/subnet_test
  allow_failure: true
  artifacts:
    paths:
    - ./subnet_test_report.xml
    reports:
      junit:
      - ./subnet_test_report.xml

.windows-netbase_getgroup:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=netbase_getgroup_report.xml
    --run_test=netbase_tests/netbase_getgroup
  allow_failure: true
  artifacts:
    paths:
    - ./netbase_getgroup_report.xml
    reports:
      junit:
      - ./netbase_getgroup_report.xml

.windows-rpc_ban:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=rpc_ban_report.xml
    --run_test=rpc_tests/rpc_ban
  allow_failure: true
  artifacts:
    paths:
    - ./rpc_ban_report.xml
    reports:
      junit:
      - ./rpc_ban_report.xml

.windows-addrman_tried_collisions:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_tried_collisions_report.xml
    --run_test=addrman_tests/addrman_tried_collisions
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_tried_collisions_report.xml
    reports:
      junit:
      - ./addrman_tried_collisions_report.xml

.windows-addrman_create:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_create_report.xml
    --run_test=addrman_tests/addrman_create
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_create_report.xml
    reports:
      junit:
      - ./addrman_create_report.xml

.windows-caddrinfo_get_tried_bucket:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=caddrinfo_get_tried_bucket_report.xml
    --run_test=addrman_tests/caddrinfo_get_tried_bucket
  allow_failure: true
  artifacts:
    paths:
    - ./caddrinfo_get_tried_bucket_report.xml
    reports:
      junit:
      - ./caddrinfo_get_tried_bucket_report.xml

.windows-addrman_getaddr:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_getaddr_report.xml
    --run_test=addrman_tests/addrman_getaddr
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_getaddr_report.xml
    reports:
      junit:
      - ./addrman_getaddr_report.xml

.windows-addrman_find:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_find_report.xml
    --run_test=addrman_tests/addrman_find
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_find_report.xml
    reports:
      junit:
      - ./addrman_find_report.xml

.windows-addrman_simple:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_simple_report.xml
    --run_test=addrman_tests/addrman_simple
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_simple_report.xml
    reports:
      junit:
      - ./addrman_simple_report.xml

.windows-addrman_new_collisions:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_new_collisions_report.xml
    --run_test=addrman_tests/addrman_new_collisions
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_new_collisions_report.xml
    reports:
      junit:
      - ./addrman_new_collisions_report.xml

.windows-caddrinfo_get_new_bucket:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=caddrinfo_get_new_bucket_report.xml
    --run_test=addrman_tests/caddrinfo_get_new_bucket
  allow_failure: true
  artifacts:
    paths:
    - ./caddrinfo_get_new_bucket_report.xml
    reports:
      junit:
      - ./caddrinfo_get_new_bucket_report.xml

.windows-addrman_ports:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_ports_report.xml
    --run_test=addrman_tests/addrman_ports
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_ports_report.xml
    reports:
      junit:
      - ./addrman_ports_report.xml

.windows-addrman_select:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_select_report.xml
    --run_test=addrman_tests/addrman_select
  allow_failure: true
  artifacts:
    paths:
    - ./addrman_select_report.xml
    reports:
      junit:
      - ./addrman_select_report.xml

.windows-miner-CreateNewBlock_validity:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --catch_system_errors=yes
    --log_level=all
    --report_level=detailed
    --report_format=XML
    --report_sink=miner_CreateNewBlock_validity_report.xml
    --run_test=miner_tests/CreateNewBlock_validity
  allow_failure: true
  artifacts:
    paths:
    - ./miner_CreateNewBlock_validity_report.xml
    reports:
      junit:
      - ./miner_CreateNewBlock_validity_report.xml

.windows-gtest-RejectsInvalidTransparentOutput:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/zcash-gtest.exe --gtest_output=xml:gtest_RejectsInvalidTransparentOutput_output.xml
                          --gtest_filter=TransactionBuilder.RejectsInvalidTransparentOutput
  allow_failure: true
  artifacts:
    reports:
      junit: ./gtest_RejectsInvalidTransparentOutput_output.xml

.windows-test_bitcoin-netbase_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=netbase_tests_report.xml
    --run_test=netbase_tests/*:!netbase_tests/netbase_networks,netbase_properties,netbase_lookupnumeric,onioncat_test,subnet_test,netbase_getgroup
  artifacts:
    paths:
    - ./netbase_tests_report.xml
    reports:
      junit:
      - ./netbase_tests_report.xml

.windows-test_bitcoin-addrman_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=addrman_tests_report.xml
    --run_test=addrman_tests/*:!addrman_tests/addrman_tried_collisions,addrman_create,caddrinfo_get_tried_bucket,addrman_getaddr,addrman_find,addrman_simple,addrman_new_collisions,caddrinfo_get_new_bucket,addrman_ports,addrman_select
  artifacts:
    paths:
    - ./addrman_tests_report.xml
    reports:
      junit:
      - ./addrman_tests_report.xml

.windows-test_bitcoin-DoS_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=DoS_tests_report.xml
    --run_test=DoS_tests/*:!DoS_tests/DoS_banning,DoS_banscore,DoS_bantime
  artifacts:
    paths:
    - ./DoS_tests_report.xml
    reports:
      junit:
      - ./DoS_tests_report.xml

.windows-test_bitcoin-rpc_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=rpc_tests_report.xml
    --run_test=rpc_tests/*:!rpc_tests/rpc_ban
  artifacts:
    paths:
    - ./rpc_tests_report.xml
    reports:
      junit:
      - ./rpc_tests_report.xml

.windows-test_bitcoin:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --help
  - ./src/test/test_bitcoin.exe --list_content=HRF
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=test_bitcoin_report.xml
    --run_test=!transaction_tests/*:!sighash_tests/*:!netbase_tests/*:!addrman_tests/*:!DoS_tests:!rpc_tests/*:!miner_tests/CreateNewBlock_validity
  artifacts:
    reports:
      junit:
      - ./test_bitcoin_report.xml

.windows-test_bitcoin-sighash_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
    --random
    --catch_system_errors=yes
    --log_format=HRF
    --log_level=test_suite
    --report_level=detailed
    --report_format=XML
    --report_sink=sighash_tests_report.xml
    --run_test=sighash_tests/*
  artifacts:
    paths:
    - ./sighash_tests_report.xml
    reports:
      junit:
      - ./sighash_tests_report.xml

.windows-test_bitcoin-transaction_tests:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/test/test_bitcoin.exe --build_info=yes
                                --random
                                --catch_system_errors=yes
                                --log_format=HRF
                                --log_level=test_suite
                                --report_level=detailed
                                --report_format=XML
                                --report_sink=transaction_tests_report.xml
                                --run_test=transaction_tests/*
  artifacts:
    paths:
    - ./transaction_tests_report.xml
    reports:
      junit:
      - ./transaction_tests_report.xml

.windows-gtest:
  stage: test
  tags:
  - windows
  - powershell
  script:
  - ./src/zcash-gtest.exe --help
  - ./src/zcash-gtest.exe --gtest_list_tests
  - ./src/zcash-gtest.exe --gtest_output=xml:gtest_output.xml
                          --gtest_shuffle
                          --gtest_filter=*:-TransactionBuilder.RejectsInvalidTransparentOutput
  artifacts:
    reports:
      junit: ./gtest_output.xml
