os: osx
addons:
  homebrew:
    packages:
      - git
      - pkgconfig
      - automake
      - autoconf
      - libtool
      - coreutils
      - ipfs
install:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - sudo pip3 install pyblake2 pyzmq
cache:
  directories:
    - "{$HOME}/Library/Application\ Support/ZcashParams"
script:
  - make -C ./depends
  - ./zcutil/build.sh -j2
  - ./qa/zcash/full_test_suite.py btest
