os: osx
addons:
  homebrew:
    packages:
      - git
      - pkg-config
      - automake
      - autoconf
      - libtool
      - coreutils
      - ipfs
install:
  - brew list
  - brew install ipfs
  - brew list
  - ipfs init
  - ipfs daemon &
  - sleep 5
  - ipfs get QmUSFo5zgPPXXejidzFWZcxVyF3AJH6Pr9br6Xisdww1r1 --output "{$HOME}/Library/Application\ Support/ZcashParams"
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - sudo pip3 install pyblake2 pyzmq
cache:
  directories:
    - "{$HOME}/Library/Application\ Support/ZcashParams"
script:
  - make -C ./depends
  - ./zcutil/build.sh -j2
  - ./qa/zcash/full_test_suite.py btest
