os: ubuntu
dist: focal
addons:
  apt:
    packages:
      - build-essential
      - pkg-config
      - libc6-dev
      - m4
      - g++-multilib
      - autoconf
      - libtool
      - ncurses-dev
      - unzip
      - git
      - python3
      - python3-zmq
      - zlib1g-dev
      - curl
      - bsdmainutils
      - automake
      - libtinfo5
install:
  - ./zcutil/clean.sh
  - sudo apt-get install \
    build-essential pkg-config libc6-dev m4 g++-multilib \
    autoconf libtool ncurses-dev unzip git python3 python3-zmq \
    zlib1g-dev curl bsdmainutils automakesudo apt-get install \
    build-essential pkg-config libc6-dev m4 g++-multilib \
    autoconf libtool ncurses-dev unzip git python3 python3-zmq \
    zlib1g-dev curl bsdmainutils automake
script:
  - HOST=x86_64-w64-mingw32 ./zcutil/build.sh -j$(nproc)
